### ISSUE TITLE
compiled version doesnt seem to work

### ISSUE THREAD

**Issue by 0lm** [iCallH4x/OCR-PY#3]
first of all, thanks for this handy tool. i tested this on python and it worked properly (after installing anoher requirement that wasnt mentioned in the requirement text file: PyAutoGui). i was curious about the compiled version, but when trying to run it, i got this "unhandled exception" error:

```
Traceback (most recent call last):
File "ocr.py", line 22, in <module>
RuntimeError: input(): lost sys.stdin
```

**Comment by BritishBenji** [comment]
The missing requirement there is my bad, I forgot to include it in my previous pull request, waiting on @iCallH4x to merge #2 to fix this.

I also receive this error, it may be due to us using `input()` instead of using command line arguments, but I'll double check with H4x as he's the one that compiled the binary

**Comment by iCallH4x** [comment]
I'll work on it - sorry for the assignment spam, GitHub mobile is awful lmao

**Comment by iCallH4x** [comment]
Should be fixed in latest release, thank you for letting me know!
